<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net4.8.1;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Version>0.0.0</Version>
    <Authors>Tim Long</Authors>
    <Company>Timtek Systems Limited</Company>
    <Product>Timtek.ReactiveCommunications</Product>
    <Description>Unit test project</Description>
    <Copyright>Copyright © 2015-2023 Timtek Systems Limited, all rights reserved</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Tigra-Astronomy/TA.ReactiveCommunications</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Tigra-Astronomy/TA.ReactiveCommunications</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>NugetPackageIcon.png</PackageIcon>
    <PackageTags>ascom,reactive,rx,communication,serial,oss</PackageTags>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
    <Title>Reactive Communications Model for connected devices</Title>
    <PackageReadmeFile>ReadMe.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;0169</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Artwork\**" />
    <EmbeddedResource Remove="Artwork\**" />
    <None Remove="Artwork\**" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\ReadMe.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="NLog.Targets.Trace" />
    <PackageReference Include="Timtek.GitFlowVersion">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Machine.Specifications.Runner.VisualStudio" />
    <PackageReference Include="Machine.Specifications.Should" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="TA.Utils.Core" />
    <PackageReference Include="TA.Utils.Logging.Nlog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Timtek.ReactiveCommunications\Timtek.ReactiveCommunications.csproj" />
  </ItemGroup>
</Project>