<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <FileUpgradeFlags>40</FileUpgradeFlags>
    <UpgradeBackupLocation>D:\VS-Projects\Timtek.reactivecommunications\Backup3\</UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Timtek.GitFlowVersion">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="NLog.Schema" />
    <PackageReference Include="NLog.Targets.Seq" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="TA.Utils.Core" />
    <PackageReference Include="TA.Utils.Logging.Nlog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Timtek.ReactiveCommunications\Timtek.ReactiveCommunications.csproj" />
    <ProjectReference Include="..\SimulatorCommunicationsChannel\SimulatorChannel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>